### ISSUE TITLE
自訂清單預設欄位名稱 (Name)

### ISSUE THREAD

**Issue by chenjenping** [howtomakeaturn/ListPower#3]
新增資料有個自動帶入的欄位叫做 Name，Name 能不能自己改成中文之類的？

<img width="426" alt="customize_name" src="https://user-images.githubusercontent.com/506568/55703841-504fea00-5a0d-11e9-8080-08107394f68d.png">

**Comment by howtomakeaturn** [comment]
目前不支援 i18n

所以也不需要 configurable、讓用戶改

應該要直接改成「名稱」比較好

我找時間弄一下～

也歡迎直接發 PR ～

**Comment by howtomakeaturn** [comment]
c3eceff6b131936e006305c191aa7b169531d5c4

**Comment by howtomakeaturn** [comment]
updated
